%% Quantile Z Up Modulated  Segment : Spike LPs
Summary_data.Up_Quant_Z_Spike_Seg(1,4:6) = [mean(CIE.Durations.Duration_Up_Units_Quantile_Segment_Spike_Means.Quant1_Seg1)...
    std(CIE.Durations.Duration_Up_Units_Quantile_Segment_Spike_Means.Quant1_Seg1)...
    size(CIE.Durations.Duration_Up_Units_Quantile_Segment_Spike_Means,1)];

Summary_data.Up_Quant_Z_Spike_Seg(2,4:6) = [mean(CIE.Durations.Duration_Up_Units_Quantile_Segment_Spike_Means.Quant1_Seg2)...
    std(CIE.Durations.Duration_Up_Units_Quantile_Segment_Spike_Means.Quant1_Seg2)...
    size(CIE.Durations.Duration_Up_Units_Quantile_Segment_Spike_Means,1)];

Summary_data.Up_Quant_Z_Spike_Seg(3,4:6) = [mean(CIE.Durations.Duration_Up_Units_Quantile_Segment_Spike_Means.Quant1_Seg3)...
    std(CIE.Durations.Duration_Up_Units_Quantile_Segment_Spike_Means.Quant1_Seg3)...
    size(CIE.Durations.Duration_Up_Units_Quantile_Segment_Spike_Means,1)];

Summary_data.Up_Quant_Z_Spike_Seg(4,4:6) = [mean(CIE.Durations.Duration_Up_Units_Quantile_Segment_Spike_Means.Quant1_Seg4)...
    std(CIE.Durations.Duration_Up_Units_Quantile_Segment_Spike_Means.Quant1_Seg4)...
    size(CIE.Durations.Duration_Up_Units_Quantile_Segment_Spike_Means,1)];



Summary_data.Up_Quant_Z_Spike_Seg(5,4:6) = [mean(CIE.Durations.Duration_Up_Units_Quantile_Segment_Spike_Means.Quant2_Seg1)...
    std(CIE.Durations.Duration_Up_Units_Quantile_Segment_Spike_Means.Quant2_Seg1)...
    size(CIE.Durations.Duration_Up_Units_Quantile_Segment_Spike_Means,1)];

Summary_data.Up_Quant_Z_Spike_Seg(6,4:6) = [mean(CIE.Durations.Duration_Up_Units_Quantile_Segment_Spike_Means.Quant2_Seg2)...
    std(CIE.Durations.Duration_Up_Units_Quantile_Segment_Spike_Means.Quant2_Seg2)...
    size(CIE.Durations.Duration_Up_Units_Quantile_Segment_Spike_Means,1)];

Summary_data.Up_Quant_Z_Spike_Seg(7,4:6) = [mean(CIE.Durations.Duration_Up_Units_Quantile_Segment_Spike_Means.Quant2_Seg3)...
    std(CIE.Durations.Duration_Up_Units_Quantile_Segment_Spike_Means.Quant2_Seg3)...
    size(CIE.Durations.Duration_Up_Units_Quantile_Segment_Spike_Means,1)];

Summary_data.Up_Quant_Z_Spike_Seg(8,4:6) = [mean(CIE.Durations.Duration_Up_Units_Quantile_Segment_Spike_Means.Quant2_Seg4)...
    std(CIE.Durations.Duration_Up_Units_Quantile_Segment_Spike_Means.Quant2_Seg4)...
    size(CIE.Durations.Duration_Up_Units_Quantile_Segment_Spike_Means,1)];



Summary_data.Up_Quant_Z_Spike_Seg(9,4:6) = [mean(CIE.Durations.Duration_Up_Units_Quantile_Segment_Spike_Means.Quant3_Seg1)...
    std(CIE.Durations.Duration_Up_Units_Quantile_Segment_Spike_Means.Quant3_Seg1)...
    size(CIE.Durations.Duration_Up_Units_Quantile_Segment_Spike_Means,1)];

Summary_data.Up_Quant_Z_Spike_Seg(10,4:6) = [mean(CIE.Durations.Duration_Up_Units_Quantile_Segment_Spike_Means.Quant3_Seg2)...
    std(CIE.Durations.Duration_Up_Units_Quantile_Segment_Spike_Means.Quant3_Seg2)...
    size(CIE.Durations.Duration_Up_Units_Quantile_Segment_Spike_Means,1)];

Summary_data.Up_Quant_Z_Spike_Seg(11,4:6) = [mean(CIE.Durations.Duration_Up_Units_Quantile_Segment_Spike_Means.Quant3_Seg3)...
    std(CIE.Durations.Duration_Up_Units_Quantile_Segment_Spike_Means.Quant3_Seg3)...
    size(CIE.Durations.Duration_Up_Units_Quantile_Segment_Spike_Means,1)];

Summary_data.Up_Quant_Z_Spike_Seg(12,4:6) = [mean(CIE.Durations.Duration_Up_Units_Quantile_Segment_Spike_Means.Quant3_Seg4)...
    std(CIE.Durations.Duration_Up_Units_Quantile_Segment_Spike_Means.Quant3_Seg4)...
    size(CIE.Durations.Duration_Up_Units_Quantile_Segment_Spike_Means,1)];



Summary_data.Up_Quant_Z_Spike_Seg(13,4:6) = [mean(CIE.Durations.Duration_Up_Units_Quantile_Segment_Spike_Means.Quant4_Seg1)...
    std(CIE.Durations.Duration_Up_Units_Quantile_Segment_Spike_Means.Quant4_Seg1)...
    size(CIE.Durations.Duration_Up_Units_Quantile_Segment_Spike_Means,1)];

Summary_data.Up_Quant_Z_Spike_Seg(14,4:6) = [mean(CIE.Durations.Duration_Up_Units_Quantile_Segment_Spike_Means.Quant4_Seg2)...
    std(CIE.Durations.Duration_Up_Units_Quantile_Segment_Spike_Means.Quant4_Seg2)...
    size(CIE.Durations.Duration_Up_Units_Quantile_Segment_Spike_Means,1)];

Summary_data.Up_Quant_Z_Spike_Seg(15,4:6) = [mean(CIE.Durations.Duration_Up_Units_Quantile_Segment_Spike_Means.Quant4_Seg3)...
    std(CIE.Durations.Duration_Up_Units_Quantile_Segment_Spike_Means.Quant4_Seg3)...
    size(CIE.Durations.Duration_Up_Units_Quantile_Segment_Spike_Means,1)];

Summary_data.Up_Quant_Z_Spike_Seg(16,4:6) = [mean(CIE.Durations.Duration_Up_Units_Quantile_Segment_Spike_Means.Quant4_Seg4)...
    std(CIE.Durations.Duration_Up_Units_Quantile_Segment_Spike_Means.Quant4_Seg4)...
    size(CIE.Durations.Duration_Up_Units_Quantile_Segment_Spike_Means,1)];


%% Quantile Z Down Modulated Segment: Spike LPs
Summary_data.Down_Quant_Z_Spike_Seg(1,4:6) = [mean(CIE.Durations.Duration_Down_Units_Quantile_Segment_Spike_Means.Quant1_Seg1)...
    std(CIE.Durations.Duration_Down_Units_Quantile_Segment_Spike_Means.Quant1_Seg1)...
    size(CIE.Durations.Duration_Down_Units_Quantile_Segment_Spike_Means,1)];

Summary_data.Down_Quant_Z_Spike_Seg(2,4:6) = [mean(CIE.Durations.Duration_Down_Units_Quantile_Segment_Spike_Means.Quant1_Seg2)...
    std(CIE.Durations.Duration_Down_Units_Quantile_Segment_Spike_Means.Quant1_Seg2)...
    size(CIE.Durations.Duration_Down_Units_Quantile_Segment_Spike_Means,1)];

Summary_data.Down_Quant_Z_Spike_Seg(3,4:6) = [mean(CIE.Durations.Duration_Down_Units_Quantile_Segment_Spike_Means.Quant1_Seg3)...
    std(CIE.Durations.Duration_Down_Units_Quantile_Segment_Spike_Means.Quant1_Seg3)...
    size(CIE.Durations.Duration_Down_Units_Quantile_Segment_Spike_Means,1)];

Summary_data.Down_Quant_Z_Spike_Seg(4,4:6) = [mean(CIE.Durations.Duration_Down_Units_Quantile_Segment_Spike_Means.Quant1_Seg4)...
    std(CIE.Durations.Duration_Down_Units_Quantile_Segment_Spike_Means.Quant1_Seg4)...
    size(CIE.Durations.Duration_Down_Units_Quantile_Segment_Spike_Means,1)];



Summary_data.Down_Quant_Z_Spike_Seg(5,4:6) = [mean(CIE.Durations.Duration_Down_Units_Quantile_Segment_Spike_Means.Quant2_Seg1)...
    std(CIE.Durations.Duration_Down_Units_Quantile_Segment_Spike_Means.Quant2_Seg1)...
    size(CIE.Durations.Duration_Down_Units_Quantile_Segment_Spike_Means,1)];

Summary_data.Down_Quant_Z_Spike_Seg(6,4:6) = [mean(CIE.Durations.Duration_Down_Units_Quantile_Segment_Spike_Means.Quant2_Seg2)...
    std(CIE.Durations.Duration_Down_Units_Quantile_Segment_Spike_Means.Quant2_Seg2)...
    size(CIE.Durations.Duration_Down_Units_Quantile_Segment_Spike_Means,1)];

Summary_data.Down_Quant_Z_Spike_Seg(7,4:6) = [mean(CIE.Durations.Duration_Down_Units_Quantile_Segment_Spike_Means.Quant2_Seg3)...
    std(CIE.Durations.Duration_Down_Units_Quantile_Segment_Spike_Means.Quant2_Seg3)...
    size(CIE.Durations.Duration_Down_Units_Quantile_Segment_Spike_Means,1)];

Summary_data.Down_Quant_Z_Spike_Seg(8,4:6) = [mean(CIE.Durations.Duration_Down_Units_Quantile_Segment_Spike_Means.Quant2_Seg4)...
    std(CIE.Durations.Duration_Down_Units_Quantile_Segment_Spike_Means.Quant2_Seg4)...
    size(CIE.Durations.Duration_Down_Units_Quantile_Segment_Spike_Means,1)];



Summary_data.Down_Quant_Z_Spike_Seg(9,4:6) = [mean(CIE.Durations.Duration_Down_Units_Quantile_Segment_Spike_Means.Quant3_Seg1)...
    std(CIE.Durations.Duration_Down_Units_Quantile_Segment_Spike_Means.Quant3_Seg1)...
    size(CIE.Durations.Duration_Down_Units_Quantile_Segment_Spike_Means,1)];

Summary_data.Down_Quant_Z_Spike_Seg(10,4:6) = [mean(CIE.Durations.Duration_Down_Units_Quantile_Segment_Spike_Means.Quant3_Seg2)...
    std(CIE.Durations.Duration_Down_Units_Quantile_Segment_Spike_Means.Quant3_Seg2)...
    size(CIE.Durations.Duration_Down_Units_Quantile_Segment_Spike_Means,1)];

Summary_data.Down_Quant_Z_Spike_Seg(11,4:6) = [mean(CIE.Durations.Duration_Down_Units_Quantile_Segment_Spike_Means.Quant3_Seg3)...
    std(CIE.Durations.Duration_Down_Units_Quantile_Segment_Spike_Means.Quant3_Seg3)...
    size(CIE.Durations.Duration_Down_Units_Quantile_Segment_Spike_Means,1)];

Summary_data.Down_Quant_Z_Spike_Seg(12,4:6) = [mean(CIE.Durations.Duration_Down_Units_Quantile_Segment_Spike_Means.Quant3_Seg4)...
    std(CIE.Durations.Duration_Down_Units_Quantile_Segment_Spike_Means.Quant3_Seg4)...
    size(CIE.Durations.Duration_Down_Units_Quantile_Segment_Spike_Means,1)];



Summary_data.Down_Quant_Z_Spike_Seg(13,4:6) = [mean(CIE.Durations.Duration_Down_Units_Quantile_Segment_Spike_Means.Quant4_Seg1)...
    std(CIE.Durations.Duration_Down_Units_Quantile_Segment_Spike_Means.Quant4_Seg1)...
    size(CIE.Durations.Duration_Down_Units_Quantile_Segment_Spike_Means,1)];

Summary_data.Down_Quant_Z_Spike_Seg(14,4:6) = [mean(CIE.Durations.Duration_Down_Units_Quantile_Segment_Spike_Means.Quant4_Seg2)...
    std(CIE.Durations.Duration_Down_Units_Quantile_Segment_Spike_Means.Quant4_Seg2)...
    size(CIE.Durations.Duration_Down_Units_Quantile_Segment_Spike_Means,1)];

Summary_data.Down_Quant_Z_Spike_Seg(15,4:6) = [mean(CIE.Durations.Duration_Down_Units_Quantile_Segment_Spike_Means.Quant4_Seg3)...
    std(CIE.Durations.Duration_Down_Units_Quantile_Segment_Spike_Means.Quant4_Seg3)...
    size(CIE.Durations.Duration_Down_Units_Quantile_Segment_Spike_Means,1)];

Summary_data.Down_Quant_Z_Spike_Seg(16,4:6) = [mean(CIE.Durations.Duration_Down_Units_Quantile_Segment_Spike_Means.Quant4_Seg4)...
    std(CIE.Durations.Duration_Down_Units_Quantile_Segment_Spike_Means.Quant4_Seg4)...
    size(CIE.Durations.Duration_Down_Units_Quantile_Segment_Spike_Means,1)];





%% Quantile Z Up Modulated Segment: All LPs
Summary_data.Up_Quant_Z_All_Seg(1,4:6) = [mean(CIE.Durations.Duration_Up_Units_Quantile_Segment_Means.Quant1_Seg1)...
    std(CIE.Durations.Duration_Up_Units_Quantile_Segment_Means.Quant1_Seg1)...
    size(CIE.Durations.Duration_Up_Units_Quantile_Segment_Means,1)];

Summary_data.Up_Quant_Z_All_Seg(2,4:6) = [mean(CIE.Durations.Duration_Up_Units_Quantile_Segment_Means.Quant1_Seg2)...
    std(CIE.Durations.Duration_Up_Units_Quantile_Segment_Means.Quant1_Seg2)...
    size(CIE.Durations.Duration_Up_Units_Quantile_Segment_Means,1)];

Summary_data.Up_Quant_Z_All_Seg(3,4:6) = [mean(CIE.Durations.Duration_Up_Units_Quantile_Segment_Means.Quant1_Seg3)...
    std(CIE.Durations.Duration_Up_Units_Quantile_Segment_Means.Quant1_Seg3)...
    size(CIE.Durations.Duration_Up_Units_Quantile_Segment_Means,1)];

Summary_data.Up_Quant_Z_All_Seg(4,4:6) = [mean(CIE.Durations.Duration_Up_Units_Quantile_Segment_Means.Quant1_Seg4)...
    std(CIE.Durations.Duration_Up_Units_Quantile_Segment_Means.Quant1_Seg4)...
    size(CIE.Durations.Duration_Up_Units_Quantile_Segment_Means,1)];



Summary_data.Up_Quant_Z_All_Seg(5,4:6) = [mean(CIE.Durations.Duration_Up_Units_Quantile_Segment_Means.Quant2_Seg1)...
    std(CIE.Durations.Duration_Up_Units_Quantile_Segment_Means.Quant2_Seg1)...
    size(CIE.Durations.Duration_Up_Units_Quantile_Segment_Means,1)];

Summary_data.Up_Quant_Z_All_Seg(6,4:6) = [mean(CIE.Durations.Duration_Up_Units_Quantile_Segment_Means.Quant2_Seg2)...
    std(CIE.Durations.Duration_Up_Units_Quantile_Segment_Means.Quant2_Seg2)...
    size(CIE.Durations.Duration_Up_Units_Quantile_Segment_Means,1)];

Summary_data.Up_Quant_Z_All_Seg(7,4:6) = [mean(CIE.Durations.Duration_Up_Units_Quantile_Segment_Means.Quant2_Seg3)...
    std(CIE.Durations.Duration_Up_Units_Quantile_Segment_Means.Quant2_Seg3)...
    size(CIE.Durations.Duration_Up_Units_Quantile_Segment_Means,1)];

Summary_data.Up_Quant_Z_All_Seg(8,4:6) = [mean(CIE.Durations.Duration_Up_Units_Quantile_Segment_Means.Quant2_Seg4)...
    std(CIE.Durations.Duration_Up_Units_Quantile_Segment_Means.Quant2_Seg4)...
    size(CIE.Durations.Duration_Up_Units_Quantile_Segment_Means,1)];



Summary_data.Up_Quant_Z_All_Seg(9,4:6) = [mean(CIE.Durations.Duration_Up_Units_Quantile_Segment_Means.Quant3_Seg1)...
    std(CIE.Durations.Duration_Up_Units_Quantile_Segment_Means.Quant3_Seg1)...
    size(CIE.Durations.Duration_Up_Units_Quantile_Segment_Means,1)];

Summary_data.Up_Quant_Z_All_Seg(10,4:6) = [mean(CIE.Durations.Duration_Up_Units_Quantile_Segment_Means.Quant3_Seg2)...
    std(CIE.Durations.Duration_Up_Units_Quantile_Segment_Means.Quant3_Seg2)...
    size(CIE.Durations.Duration_Up_Units_Quantile_Segment_Means,1)];

Summary_data.Up_Quant_Z_All_Seg(11,4:6) = [mean(CIE.Durations.Duration_Up_Units_Quantile_Segment_Means.Quant3_Seg3)...
    std(CIE.Durations.Duration_Up_Units_Quantile_Segment_Means.Quant3_Seg3)...
    size(CIE.Durations.Duration_Up_Units_Quantile_Segment_Means,1)];

Summary_data.Up_Quant_Z_All_Seg(12,4:6) = [mean(CIE.Durations.Duration_Up_Units_Quantile_Segment_Means.Quant3_Seg4)...
    std(CIE.Durations.Duration_Up_Units_Quantile_Segment_Means.Quant3_Seg4)...
    size(CIE.Durations.Duration_Up_Units_Quantile_Segment_Means,1)];



Summary_data.Up_Quant_Z_All_Seg(13,4:6) = [mean(CIE.Durations.Duration_Up_Units_Quantile_Segment_Means.Quant4_Seg1)...
    std(CIE.Durations.Duration_Up_Units_Quantile_Segment_Means.Quant4_Seg1)...
    size(CIE.Durations.Duration_Up_Units_Quantile_Segment_Means,1)];

Summary_data.Up_Quant_Z_All_Seg(14,4:6) = [mean(CIE.Durations.Duration_Up_Units_Quantile_Segment_Means.Quant4_Seg2)...
    std(CIE.Durations.Duration_Up_Units_Quantile_Segment_Means.Quant4_Seg2)...
    size(CIE.Durations.Duration_Up_Units_Quantile_Segment_Means,1)];

Summary_data.Up_Quant_Z_All_Seg(15,4:6) = [mean(CIE.Durations.Duration_Up_Units_Quantile_Segment_Means.Quant4_Seg3)...
    std(CIE.Durations.Duration_Up_Units_Quantile_Segment_Means.Quant4_Seg3)...
    size(CIE.Durations.Duration_Up_Units_Quantile_Segment_Means,1)];

Summary_data.Up_Quant_Z_All_Seg(16,4:6) = [mean(CIE.Durations.Duration_Up_Units_Quantile_Segment_Means.Quant4_Seg4)...
    std(CIE.Durations.Duration_Up_Units_Quantile_Segment_Means.Quant4_Seg4)...
    size(CIE.Durations.Duration_Up_Units_Quantile_Segment_Means,1)];


%% Quantile Z Down Modulated Segment: All LPs
Summary_data.Down_Quant_Z_All_Seg(1,4:6) = [mean(CIE.Durations.Duration_Down_Units_Quantile_Segment_Means.Quant1_Seg1)...
    std(CIE.Durations.Duration_Down_Units_Quantile_Segment_Means.Quant1_Seg1)...
    size(CIE.Durations.Duration_Down_Units_Quantile_Segment_Means,1)];

Summary_data.Down_Quant_Z_All_Seg(2,4:6) = [mean(CIE.Durations.Duration_Down_Units_Quantile_Segment_Means.Quant1_Seg2)...
    std(CIE.Durations.Duration_Down_Units_Quantile_Segment_Means.Quant1_Seg2)...
    size(CIE.Durations.Duration_Down_Units_Quantile_Segment_Means,1)];

Summary_data.Down_Quant_Z_All_Seg(3,4:6) = [mean(CIE.Durations.Duration_Down_Units_Quantile_Segment_Means.Quant1_Seg3)...
    std(CIE.Durations.Duration_Down_Units_Quantile_Segment_Means.Quant1_Seg3)...
    size(CIE.Durations.Duration_Down_Units_Quantile_Segment_Means,1)];

Summary_data.Down_Quant_Z_All_Seg(4,4:6) = [mean(CIE.Durations.Duration_Down_Units_Quantile_Segment_Means.Quant1_Seg4)...
    std(CIE.Durations.Duration_Down_Units_Quantile_Segment_Means.Quant1_Seg4)...
    size(CIE.Durations.Duration_Down_Units_Quantile_Segment_Means,1)];



Summary_data.Down_Quant_Z_All_Seg(5,4:6) = [mean(CIE.Durations.Duration_Down_Units_Quantile_Segment_Means.Quant2_Seg1)...
    std(CIE.Durations.Duration_Down_Units_Quantile_Segment_Means.Quant2_Seg1)...
    size(CIE.Durations.Duration_Down_Units_Quantile_Segment_Means,1)];

Summary_data.Down_Quant_Z_All_Seg(6,4:6) = [mean(CIE.Durations.Duration_Down_Units_Quantile_Segment_Means.Quant2_Seg2)...
    std(CIE.Durations.Duration_Down_Units_Quantile_Segment_Means.Quant2_Seg2)...
    size(CIE.Durations.Duration_Down_Units_Quantile_Segment_Means,1)];

Summary_data.Down_Quant_Z_All_Seg(7,4:6) = [mean(CIE.Durations.Duration_Down_Units_Quantile_Segment_Means.Quant2_Seg3)...
    std(CIE.Durations.Duration_Down_Units_Quantile_Segment_Means.Quant2_Seg3)...
    size(CIE.Durations.Duration_Down_Units_Quantile_Segment_Means,1)];

Summary_data.Down_Quant_Z_All_Seg(8,4:6) = [mean(CIE.Durations.Duration_Down_Units_Quantile_Segment_Means.Quant2_Seg4)...
    std(CIE.Durations.Duration_Down_Units_Quantile_Segment_Means.Quant2_Seg4)...
    size(CIE.Durations.Duration_Down_Units_Quantile_Segment_Means,1)];



Summary_data.Down_Quant_Z_All_Seg(9,4:6) = [mean(CIE.Durations.Duration_Down_Units_Quantile_Segment_Means.Quant3_Seg1)...
    std(CIE.Durations.Duration_Down_Units_Quantile_Segment_Means.Quant3_Seg1)...
    size(CIE.Durations.Duration_Down_Units_Quantile_Segment_Means,1)];

Summary_data.Down_Quant_Z_All_Seg(10,4:6) = [mean(CIE.Durations.Duration_Down_Units_Quantile_Segment_Means.Quant3_Seg2)...
    std(CIE.Durations.Duration_Down_Units_Quantile_Segment_Means.Quant3_Seg2)...
    size(CIE.Durations.Duration_Down_Units_Quantile_Segment_Means,1)];

Summary_data.Down_Quant_Z_All_Seg(11,4:6) = [mean(CIE.Durations.Duration_Down_Units_Quantile_Segment_Means.Quant3_Seg3)...
    std(CIE.Durations.Duration_Down_Units_Quantile_Segment_Means.Quant3_Seg3)...
    size(CIE.Durations.Duration_Down_Units_Quantile_Segment_Means,1)];

Summary_data.Down_Quant_Z_All_Seg(12,4:6) = [mean(CIE.Durations.Duration_Down_Units_Quantile_Segment_Means.Quant3_Seg4)...
    std(CIE.Durations.Duration_Down_Units_Quantile_Segment_Means.Quant3_Seg4)...
    size(CIE.Durations.Duration_Down_Units_Quantile_Segment_Means,1)];



Summary_data.Down_Quant_Z_All_Seg(13,4:6) = [mean(CIE.Durations.Duration_Down_Units_Quantile_Segment_Means.Quant4_Seg1)...
    std(CIE.Durations.Duration_Down_Units_Quantile_Segment_Means.Quant4_Seg1)...
    size(CIE.Durations.Duration_Down_Units_Quantile_Segment_Means,1)];

Summary_data.Down_Quant_Z_All_Seg(14,4:6) = [mean(CIE.Durations.Duration_Down_Units_Quantile_Segment_Means.Quant4_Seg2)...
    std(CIE.Durations.Duration_Down_Units_Quantile_Segment_Means.Quant4_Seg2)...
    size(CIE.Durations.Duration_Down_Units_Quantile_Segment_Means,1)];

Summary_data.Down_Quant_Z_All_Seg(15,4:6) = [mean(CIE.Durations.Duration_Down_Units_Quantile_Segment_Means.Quant4_Seg3)...
    std(CIE.Durations.Duration_Down_Units_Quantile_Segment_Means.Quant4_Seg3)...
    size(CIE.Durations.Duration_Down_Units_Quantile_Segment_Means,1)];

Summary_data.Down_Quant_Z_All_Seg(16,4:6) = [mean(CIE.Durations.Duration_Down_Units_Quantile_Segment_Means.Quant4_Seg4)...
    std(CIE.Durations.Duration_Down_Units_Quantile_Segment_Means.Quant4_Seg4)...
    size(CIE.Durations.Duration_Down_Units_Quantile_Segment_Means,1)];