%% Quantile Z Up Modulated: All LPs
Summary_data.Up_Quant_Z_All(1,1:3) = [mean(Air.Duration.Duration_Up_Units_Quantile_Means.Quant1)...
    std(Air.Duration.Duration_Up_Units_Quantile_Means.Quant1)...
    size(Air.Duration.Duration_Up_Units_Quantile_Means,1)];

Summary_data.Up_Quant_Z_All(2,1:3) = [mean(Air.Duration.Duration_Up_Units_Quantile_Means.Quant2)...
    std(Air.Duration.Duration_Up_Units_Quantile_Means.Quant2)...
    size(Air.Duration.Duration_Up_Units_Quantile_Means,1)];

Summary_data.Up_Quant_Z_All(3,1:3) = [mean(Air.Duration.Duration_Up_Units_Quantile_Means.Quant3)...
    std(Air.Duration.Duration_Up_Units_Quantile_Means.Quant3)...
    size(Air.Duration.Duration_Up_Units_Quantile_Means,1)];

Summary_data.Up_Quant_Z_All(4,1:3) = [mean(Air.Duration.Duration_Up_Units_Quantile_Means.Quant4)...
    std(Air.Duration.Duration_Up_Units_Quantile_Means.Quant4)...
    size(Air.Duration.Duration_Up_Units_Quantile_Means,1)];


%% Quantile Z Up Modulated: All LPs

Summary_data.Down_Quant_Z_All(1,1:3) = [mean(Air.Duration.Duration_Down_Units_Quantile_Means.Quant1)...
    std(Air.Duration.Duration_Down_Units_Quantile_Means.Quant1)...
    size(Air.Duration.Duration_Down_Units_Quantile_Means,1)];

Summary_data.Down_Quant_Z_All(2,1:3) = [mean(Air.Duration.Duration_Down_Units_Quantile_Means.Quant2)...
    std(Air.Duration.Duration_Down_Units_Quantile_Means.Quant2)...
    size(Air.Duration.Duration_Down_Units_Quantile_Means,1)];

Summary_data.Down_Quant_Z_All(3,1:3) = [mean(Air.Duration.Duration_Down_Units_Quantile_Means.Quant3)...
    std(Air.Duration.Duration_Down_Units_Quantile_Means.Quant3)...
    size(Air.Duration.Duration_Down_Units_Quantile_Means,1)];

Summary_data.Down_Quant_Z_All(4,1:3) = [mean(Air.Duration.Duration_Down_Units_Quantile_Means.Quant4)...
    std(Air.Duration.Duration_Down_Units_Quantile_Means.Quant4)...
    size(Air.Duration.Duration_Down_Units_Quantile_Means,1)];


%% Quantile Z Up Modulated: Spike LPs
Summary_data.Up_Quant_Z_Spike(1,1:3) = [mean(Air.Duration.Duration_Up_Units_Quantile_Spikes_Means.Quant1)...
    std(Air.Duration.Duration_Up_Units_Quantile_Spikes_Means.Quant1)...
    size(Air.Duration.Duration_Up_Units_Quantile_Spikes_Means,1)];

Summary_data.Up_Quant_Z_Spike(2,1:3) = [mean(Air.Duration.Duration_Up_Units_Quantile_Spikes_Means.Quant2)...
    std(Air.Duration.Duration_Up_Units_Quantile_Spikes_Means.Quant2)...
    size(Air.Duration.Duration_Up_Units_Quantile_Spikes_Means,1)];

Summary_data.Up_Quant_Z_Spike(3,1:3) = [mean(Air.Duration.Duration_Up_Units_Quantile_Spikes_Means.Quant3)...
    std(Air.Duration.Duration_Up_Units_Quantile_Spikes_Means.Quant3)...
    size(Air.Duration.Duration_Up_Units_Quantile_Spikes_Means,1)];

Summary_data.Up_Quant_Z_Spike(4,1:3) = [mean(Air.Duration.Duration_Up_Units_Quantile_Spikes_Means.Quant4)...
    std(Air.Duration.Duration_Up_Units_Quantile_Spikes_Means.Quant4)...
    size(Air.Duration.Duration_Up_Units_Quantile_Spikes_Means,1)];


%% Quantile Z Down Modulated: Spike LPs
Summary_data.Down_Quant_Z_Spike(1,1:3) = [mean(Air.Duration.Duration_Down_Units_Quantile_Spikes_Means.Quant1)...
    std(Air.Duration.Duration_Down_Units_Quantile_Spikes_Means.Quant1)...
    size(Air.Duration.Duration_Down_Units_Quantile_Spikes_Means,1)];

Summary_data.Down_Quant_Z_Spike(2,1:3) = [mean(Air.Duration.Duration_Down_Units_Quantile_Spikes_Means.Quant2)...
    std(Air.Duration.Duration_Down_Units_Quantile_Spikes_Means.Quant2)...
    size(Air.Duration.Duration_Down_Units_Quantile_Spikes_Means,1)];

Summary_data.Down_Quant_Z_Spike(3,1:3) = [mean(Air.Duration.Duration_Down_Units_Quantile_Spikes_Means.Quant3)...
    std(Air.Duration.Duration_Down_Units_Quantile_Spikes_Means.Quant3)...
    size(Air.Duration.Duration_Down_Units_Quantile_Spikes_Means,1)];

Summary_data.Down_Quant_Z_Spike(4,1:3) = [mean(Air.Duration.Duration_Down_Units_Quantile_Spikes_Means.Quant4)...
    std(Air.Duration.Duration_Down_Units_Quantile_Spikes_Means.Quant4)...
    size(Air.Duration.Duration_Down_Units_Quantile_Spikes_Means,1)];



%% Proportion: Up Modulated: Spike LPs
Summary_data.Up_Segment_Proportion(1,1:3) = [mean(Air.Duration.Duration_Up_Units_Segment_Proportion_Means.Seg1)...
    std(Air.Duration.Duration_Up_Units_Segment_Proportion_Means.Seg1)...
    size(Air.Duration.Duration_Up_Units_Segment_Proportion_Means,1)];

Summary_data.Up_Segment_Proportion(2,1:3) = [mean(Air.Duration.Duration_Up_Units_Segment_Proportion_Means.Seg2)...
    std(Air.Duration.Duration_Up_Units_Segment_Proportion_Means.Seg2)...
    size(Air.Duration.Duration_Up_Units_Segment_Proportion_Means,1)];

Summary_data.Up_Segment_Proportion(3,1:3) = [mean(Air.Duration.Duration_Up_Units_Segment_Proportion_Means.Seg3)...
    std(Air.Duration.Duration_Up_Units_Segment_Proportion_Means.Seg3)...
    size(Air.Duration.Duration_Up_Units_Segment_Proportion_Means,1)];

Summary_data.Up_Segment_Proportion(4,1:3) = [mean(Air.Duration.Duration_Up_Units_Segment_Proportion_Means.Seg4)...
    std(Air.Duration.Duration_Up_Units_Segment_Proportion_Means.Seg4)...
    size(Air.Duration.Duration_Up_Units_Segment_Proportion_Means,1)];

%% Proportion: Down Modulated: Spike LPs
Summary_data.Down_Segment_Proportion(1,1:3) = [mean(Air.Duration.Duration_Down_Units_Segment_Proportion_Means.Seg1)...
    std(Air.Duration.Duration_Down_Units_Segment_Proportion_Means.Seg1)...
    size(Air.Duration.Duration_Down_Units_Segment_Proportion_Means,1)];
Summary_data.Down_Segment_Proportion(2,1:3) = [mean(Air.Duration.Duration_Down_Units_Segment_Proportion_Means.Seg2)...
    std(Air.Duration.Duration_Down_Units_Segment_Proportion_Means.Seg2)...
    size(Air.Duration.Duration_Down_Units_Segment_Proportion_Means,1)];
Summary_data.Down_Segment_Proportion(3,1:3) = [mean(Air.Duration.Duration_Down_Units_Segment_Proportion_Means.Seg3)...
    std(Air.Duration.Duration_Down_Units_Segment_Proportion_Means.Seg3)...
    size(Air.Duration.Duration_Down_Units_Segment_Proportion_Means,1)];
Summary_data.Down_Segment_Proportion(4,1:3) = [mean(Air.Duration.Duration_Down_Units_Segment_Proportion_Means.Seg4)...
    std(Air.Duration.Duration_Down_Units_Segment_Proportion_Means.Seg4)...
    size(Air.Duration.Duration_Down_Units_Segment_Proportion_Means,1)];



%% Quantile Z Up Modulated: All Spikes
Summary_data.Up_Quant_Z_All(1,4:6) = [mean(CIE.Duration.Duration_Up_Units_Quantile_Means.Quant1)...
    std(CIE.Duration.Duration_Up_Units_Quantile_Means.Quant1)...
    size(CIE.Duration.Duration_Up_Units_Quantile_Means,1)];

Summary_data.Up_Quant_Z_All(2,4:6) = [mean(CIE.Duration.Duration_Up_Units_Quantile_Means.Quant2)...
    std(CIE.Duration.Duration_Up_Units_Quantile_Means.Quant2)...
    size(CIE.Duration.Duration_Up_Units_Quantile_Means,1)];

Summary_data.Up_Quant_Z_All(3,4:6) = [mean(CIE.Duration.Duration_Up_Units_Quantile_Means.Quant3)...
    std(CIE.Duration.Duration_Up_Units_Quantile_Means.Quant3)...
    size(CIE.Duration.Duration_Up_Units_Quantile_Means,1)];

Summary_data.Up_Quant_Z_All(4,4:6) = [mean(CIE.Duration.Duration_Up_Units_Quantile_Means.Quant4)...
    std(CIE.Duration.Duration_Up_Units_Quantile_Means.Quant4)...
    size(CIE.Duration.Duration_Up_Units_Quantile_Means,1)];

%% Quantile Z Up Modulated: All Spikes

Summary_data.Down_Quant_Z_All(1,4:6) = [mean(CIE.Duration.Duration_Down_Units_Quantile_Means.Quant1)...
    std(CIE.Duration.Duration_Down_Units_Quantile_Means.Quant1)...
    size(CIE.Duration.Duration_Down_Units_Quantile_Means,1)];

Summary_data.Down_Quant_Z_All(2,4:6) = [mean(CIE.Duration.Duration_Down_Units_Quantile_Means.Quant2)...
    std(CIE.Duration.Duration_Down_Units_Quantile_Means.Quant2)...
    size(CIE.Duration.Duration_Down_Units_Quantile_Means,1)];

Summary_data.Down_Quant_Z_All(3,4:6) = [mean(CIE.Duration.Duration_Down_Units_Quantile_Means.Quant3)...
    std(CIE.Duration.Duration_Down_Units_Quantile_Means.Quant3)...
    size(CIE.Duration.Duration_Down_Units_Quantile_Means,1)];

Summary_data.Down_Quant_Z_All(4,4:6) = [mean(CIE.Duration.Duration_Down_Units_Quantile_Means.Quant4)...
    std(CIE.Duration.Duration_Down_Units_Quantile_Means.Quant4)...
    size(CIE.Duration.Duration_Down_Units_Quantile_Means,1)];


%% Quantile Z Up Modulated: Spike LPs
Summary_data.Up_Quant_Z_Spike(1,4:6) = [mean(CIE.Duration.Duration_Up_Units_Quantile_Spikes_Means.Quant1)...
    std(CIE.Duration.Duration_Up_Units_Quantile_Spikes_Means.Quant1)...
    size(CIE.Duration.Duration_Up_Units_Quantile_Spikes_Means,1)];

Summary_data.Up_Quant_Z_Spike(2,4:6) = [mean(CIE.Duration.Duration_Up_Units_Quantile_Spikes_Means.Quant2)...
    std(CIE.Duration.Duration_Up_Units_Quantile_Spikes_Means.Quant2)...
    size(CIE.Duration.Duration_Up_Units_Quantile_Spikes_Means,1)];

Summary_data.Up_Quant_Z_Spike(3,4:6) = [mean(CIE.Duration.Duration_Up_Units_Quantile_Spikes_Means.Quant3)...
    std(CIE.Duration.Duration_Up_Units_Quantile_Spikes_Means.Quant3)...
    size(CIE.Duration.Duration_Up_Units_Quantile_Spikes_Means,1)];

Summary_data.Up_Quant_Z_Spike(4,4:6) = [mean(CIE.Duration.Duration_Up_Units_Quantile_Spikes_Means.Quant4)...
    std(CIE.Duration.Duration_Up_Units_Quantile_Spikes_Means.Quant4)...
    size(CIE.Duration.Duration_Up_Units_Quantile_Spikes_Means,1)];




%% Quantile Z Down Modulated: Spike LPs
Summary_data.Down_Quant_Z_Spike(1,4:6) = [mean(CIE.Duration.Duration_Down_Units_Quantile_Spikes_Means.Quant1)...
    std(CIE.Duration.Duration_Down_Units_Quantile_Spikes_Means.Quant1)...
    size(CIE.Duration.Duration_Down_Units_Quantile_Spikes_Means,1)];

Summary_data.Down_Quant_Z_Spike(2,4:6) = [mean(CIE.Duration.Duration_Down_Units_Quantile_Spikes_Means.Quant2)...
    std(CIE.Duration.Duration_Down_Units_Quantile_Spikes_Means.Quant2)...
    size(CIE.Duration.Duration_Down_Units_Quantile_Spikes_Means,1)];

Summary_data.Down_Quant_Z_Spike(3,4:6) = [mean(CIE.Duration.Duration_Down_Units_Quantile_Spikes_Means.Quant3)...
    std(CIE.Duration.Duration_Down_Units_Quantile_Spikes_Means.Quant3)...
    size(CIE.Duration.Duration_Down_Units_Quantile_Spikes_Means,1)];

Summary_data.Down_Quant_Z_Spike(4,4:6) = [mean(CIE.Duration.Duration_Down_Units_Quantile_Spikes_Means.Quant4)...
    std(CIE.Duration.Duration_Down_Units_Quantile_Spikes_Means.Quant4)...
    size(CIE.Duration.Duration_Down_Units_Quantile_Spikes_Means,1)];



%% Proportion: Up Modulated: Spike LPs
Summary_data.Up_Segment_Proportion(1,4:6) = [mean(CIE.Duration.Duration_Up_Units_Segment_Proportion_Means.Seg1)...
    std(CIE.Duration.Duration_Up_Units_Segment_Proportion_Means.Seg1)...
    size(CIE.Duration.Duration_Up_Units_Segment_Proportion_Means,1)];

Summary_data.Up_Segment_Proportion(2,4:6) = [mean(CIE.Duration.Duration_Up_Units_Segment_Proportion_Means.Seg2)...
    std(CIE.Duration.Duration_Up_Units_Segment_Proportion_Means.Seg2)...
    size(CIE.Duration.Duration_Up_Units_Segment_Proportion_Means,1)];

Summary_data.Up_Segment_Proportion(3,4:6) = [mean(CIE.Duration.Duration_Up_Units_Segment_Proportion_Means.Seg3)...
    std(CIE.Duration.Duration_Up_Units_Segment_Proportion_Means.Seg3)...
    size(CIE.Duration.Duration_Up_Units_Segment_Proportion_Means,1)];

Summary_data.Up_Segment_Proportion(4,4:6) = [mean(CIE.Duration.Duration_Up_Units_Segment_Proportion_Means.Seg4)...
    std(CIE.Duration.Duration_Up_Units_Segment_Proportion_Means.Seg4)...
    size(CIE.Duration.Duration_Up_Units_Segment_Proportion_Means,1)];

%% Proportion: Down Modulated: Spike LPs
Summary_data.Down_Segment_Proportion(1,4:6) = [mean(CIE.Duration.Duration_Down_Units_Segment_Proportion_Means.Seg1)...
    std(CIE.Duration.Duration_Down_Units_Segment_Proportion_Means.Seg1)...
    size(CIE.Duration.Duration_Down_Units_Segment_Proportion_Means,1)];
Summary_data.Down_Segment_Proportion(2,4:6) = [mean(CIE.Duration.Duration_Down_Units_Segment_Proportion_Means.Seg2)...
    std(CIE.Duration.Duration_Down_Units_Segment_Proportion_Means.Seg2)...
    size(CIE.Duration.Duration_Down_Units_Segment_Proportion_Means,1)];
Summary_data.Down_Segment_Proportion(3,4:6) = [mean(CIE.Duration.Duration_Down_Units_Segment_Proportion_Means.Seg3)...
    std(CIE.Duration.Duration_Down_Units_Segment_Proportion_Means.Seg3)...
    size(CIE.Duration.Duration_Down_Units_Segment_Proportion_Means,1)];
Summary_data.Down_Segment_Proportion(4,4:6) = [mean(CIE.Duration.Duration_Down_Units_Segment_Proportion_Means.Seg4)...
    std(CIE.Duration.Duration_Down_Units_Segment_Proportion_Means.Seg4)...
    size(CIE.Duration.Duration_Down_Units_Segment_Proportion_Means,1)];









%% Proportion: Up Modulated: Spike LPs: Success
Summary_data.Up_Segment_Proportion_Succ(1,1:3) = [mean(Air.Duration.Duration_Up_Units_Segment_Proportion_Means_Succ.Seg1)...
    std(Air.Duration.Duration_Up_Units_Segment_Proportion_Means_Succ.Seg1)...
    size(Air.Duration.Duration_Up_Units_Segment_Proportion_Means_Succ,1)];

Summary_data.Up_Segment_Proportion_Succ(2,1:3) = [mean(Air.Duration.Duration_Up_Units_Segment_Proportion_Means_Succ.Seg2)...
    std(Air.Duration.Duration_Up_Units_Segment_Proportion_Means_Succ.Seg2)...
    size(Air.Duration.Duration_Up_Units_Segment_Proportion_Means_Succ,1)];

Summary_data.Up_Segment_Proportion_Succ(3,1:3) = [mean(Air.Duration.Duration_Up_Units_Segment_Proportion_Means_Succ.Seg3)...
    std(Air.Duration.Duration_Up_Units_Segment_Proportion_Means_Succ.Seg3)...
    size(Air.Duration.Duration_Up_Units_Segment_Proportion_Means_Succ,1)];

Summary_data.Up_Segment_Proportion_Succ(4,1:3) = [mean(Air.Duration.Duration_Up_Units_Segment_Proportion_Means_Succ.Seg4)...
    std(Air.Duration.Duration_Up_Units_Segment_Proportion_Means_Succ.Seg4)...
    size(Air.Duration.Duration_Up_Units_Segment_Proportion_Means_Succ,1)];

%% Proportion: Down Modulated: Spike LPs: Success
Summary_data.Down_Segment_Proportion_Succ(1,1:3) = [mean(Air.Duration.Duration_Down_Units_Segment_Proportion_Means_Succ.Seg1)...
    std(Air.Duration.Duration_Down_Units_Segment_Proportion_Means_Succ.Seg1)...
    size(Air.Duration.Duration_Down_Units_Segment_Proportion_Means_Succ,1)];
Summary_data.Down_Segment_Proportion_Succ(2,1:3) = [mean(Air.Duration.Duration_Down_Units_Segment_Proportion_Means_Succ.Seg2)...
    std(Air.Duration.Duration_Down_Units_Segment_Proportion_Means_Succ.Seg2)...
    size(Air.Duration.Duration_Down_Units_Segment_Proportion_Means_Succ,1)];
Summary_data.Down_Segment_Proportion_Succ(3,1:3) = [mean(Air.Duration.Duration_Down_Units_Segment_Proportion_Means_Succ.Seg3)...
    std(Air.Duration.Duration_Down_Units_Segment_Proportion_Means_Succ.Seg3)...
    size(Air.Duration.Duration_Down_Units_Segment_Proportion_Means_Succ,1)];
Summary_data.Down_Segment_Proportion_Succ(4,1:3) = [mean(Air.Duration.Duration_Down_Units_Segment_Proportion_Means_Succ.Seg4)...
    std(Air.Duration.Duration_Down_Units_Segment_Proportion_Means_Succ.Seg4)...
    size(Air.Duration.Duration_Down_Units_Segment_Proportion_Means_Succ,1)];


%% Proportion: Up Modulated: Spike LPs: Success
Summary_data.Up_Segment_Proportion_Succ(1,4:6) = [mean(CIE.Duration.Duration_Up_Units_Segment_Proportion_Means_Succ.Seg1)...
    std(CIE.Duration.Duration_Up_Units_Segment_Proportion_Means_Succ.Seg1)...
    size(CIE.Duration.Duration_Up_Units_Segment_Proportion_Means_Succ,1)];

Summary_data.Up_Segment_Proportion_Succ(2,4:6) = [mean(CIE.Duration.Duration_Up_Units_Segment_Proportion_Means_Succ.Seg2)...
    std(CIE.Duration.Duration_Up_Units_Segment_Proportion_Means_Succ.Seg2)...
    size(CIE.Duration.Duration_Up_Units_Segment_Proportion_Means_Succ,1)];

Summary_data.Up_Segment_Proportion_Succ(3,4:6) = [mean(CIE.Duration.Duration_Up_Units_Segment_Proportion_Means_Succ.Seg3)...
    std(CIE.Duration.Duration_Up_Units_Segment_Proportion_Means_Succ.Seg3)...
    size(CIE.Duration.Duration_Up_Units_Segment_Proportion_Means_Succ,1)];

Summary_data.Up_Segment_Proportion_Succ(4,4:6) = [mean(CIE.Duration.Duration_Up_Units_Segment_Proportion_Means_Succ.Seg4)...
    std(CIE.Duration.Duration_Up_Units_Segment_Proportion_Means_Succ.Seg4)...
    size(CIE.Duration.Duration_Up_Units_Segment_Proportion_Means_Succ,1)];

%% Proportion: Down Modulated: Spike LPs: Success
Summary_data.Down_Segment_Proportion_Succ(1,4:6) = [mean(CIE.Duration.Duration_Down_Units_Segment_Proportion_Means_Succ.Seg1)...
    std(CIE.Duration.Duration_Down_Units_Segment_Proportion_Means_Succ.Seg1)...
    size(CIE.Duration.Duration_Down_Units_Segment_Proportion_Means_Succ,1)];
Summary_data.Down_Segment_Proportion_Succ(2,4:6) = [mean(CIE.Duration.Duration_Down_Units_Segment_Proportion_Means_Succ.Seg2)...
    std(CIE.Duration.Duration_Down_Units_Segment_Proportion_Means_Succ.Seg2)...
    size(CIE.Duration.Duration_Down_Units_Segment_Proportion_Means_Succ,1)];
Summary_data.Down_Segment_Proportion_Succ(3,4:6) = [mean(CIE.Duration.Duration_Down_Units_Segment_Proportion_Means_Succ.Seg3)...
    std(CIE.Duration.Duration_Down_Units_Segment_Proportion_Means_Succ.Seg3)...
    size(CIE.Duration.Duration_Down_Units_Segment_Proportion_Means_Succ,1)];
Summary_data.Down_Segment_Proportion_Succ(4,4:6) = [mean(CIE.Duration.Duration_Down_Units_Segment_Proportion_Means_Succ.Seg4)...
    std(CIE.Duration.Duration_Down_Units_Segment_Proportion_Means_Succ.Seg4)...
    size(CIE.Duration.Duration_Down_Units_Segment_Proportion_Means_Succ,1)];





%% Quantile Z Up Modulated  Segment : Spike LPs
Summary_data.Up_Quant_Z_Spike_Seg(1,1:3) = [mean(Air.Duration.Duration_Up_Units_Quantile_Segment_Spike_Means.Quant1_Seg1)...
    std(Air.Duration.Duration_Up_Units_Quantile_Segment_Spike_Means.Quant1_Seg1)...
    size(Air.Duration.Duration_Up_Units_Quantile_Segment_Spike_Means,1)];

Summary_data.Up_Quant_Z_Spike_Seg(2,1:3) = [mean(Air.Duration.Duration_Up_Units_Quantile_Segment_Spike_Means.Quant1_Seg2)...
    std(Air.Duration.Duration_Up_Units_Quantile_Segment_Spike_Means.Quant1_Seg2)...
    size(Air.Duration.Duration_Up_Units_Quantile_Segment_Spike_Means,1)];

Summary_data.Up_Quant_Z_Spike_Seg(3,1:3) = [mean(Air.Duration.Duration_Up_Units_Quantile_Segment_Spike_Means.Quant1_Seg3)...
    std(Air.Duration.Duration_Up_Units_Quantile_Segment_Spike_Means.Quant1_Seg3)...
    size(Air.Duration.Duration_Up_Units_Quantile_Segment_Spike_Means,1)];

Summary_data.Up_Quant_Z_Spike_Seg(4,1:3) = [mean(Air.Duration.Duration_Up_Units_Quantile_Segment_Spike_Means.Quant1_Seg4)...
    std(Air.Duration.Duration_Up_Units_Quantile_Segment_Spike_Means.Quant1_Seg4)...
    size(Air.Duration.Duration_Up_Units_Quantile_Segment_Spike_Means,1)];



Summary_data.Up_Quant_Z_Spike_Seg(5,1:3) = [mean(Air.Duration.Duration_Up_Units_Quantile_Segment_Spike_Means.Quant2_Seg1)...
    std(Air.Duration.Duration_Up_Units_Quantile_Segment_Spike_Means.Quant2_Seg1)...
    size(Air.Duration.Duration_Up_Units_Quantile_Segment_Spike_Means,1)];

Summary_data.Up_Quant_Z_Spike_Seg(6,1:3) = [mean(Air.Duration.Duration_Up_Units_Quantile_Segment_Spike_Means.Quant2_Seg2)...
    std(Air.Duration.Duration_Up_Units_Quantile_Segment_Spike_Means.Quant2_Seg2)...
    size(Air.Duration.Duration_Up_Units_Quantile_Segment_Spike_Means,1)];

Summary_data.Up_Quant_Z_Spike_Seg(7,1:3) = [mean(Air.Duration.Duration_Up_Units_Quantile_Segment_Spike_Means.Quant2_Seg3)...
    std(Air.Duration.Duration_Up_Units_Quantile_Segment_Spike_Means.Quant2_Seg3)...
    size(Air.Duration.Duration_Up_Units_Quantile_Segment_Spike_Means,1)];

Summary_data.Up_Quant_Z_Spike_Seg(8,1:3) = [mean(Air.Duration.Duration_Up_Units_Quantile_Segment_Spike_Means.Quant2_Seg4)...
    std(Air.Duration.Duration_Up_Units_Quantile_Segment_Spike_Means.Quant2_Seg4)...
    size(Air.Duration.Duration_Up_Units_Quantile_Segment_Spike_Means,1)];



Summary_data.Up_Quant_Z_Spike_Seg(9,1:3) = [mean(Air.Duration.Duration_Up_Units_Quantile_Segment_Spike_Means.Quant3_Seg1)...
    std(Air.Duration.Duration_Up_Units_Quantile_Segment_Spike_Means.Quant3_Seg1)...
    size(Air.Duration.Duration_Up_Units_Quantile_Segment_Spike_Means,1)];

Summary_data.Up_Quant_Z_Spike_Seg(10,1:3) = [mean(Air.Duration.Duration_Up_Units_Quantile_Segment_Spike_Means.Quant3_Seg2)...
    std(Air.Duration.Duration_Up_Units_Quantile_Segment_Spike_Means.Quant3_Seg2)...
    size(Air.Duration.Duration_Up_Units_Quantile_Segment_Spike_Means,1)];

Summary_data.Up_Quant_Z_Spike_Seg(11,1:3) = [mean(Air.Duration.Duration_Up_Units_Quantile_Segment_Spike_Means.Quant3_Seg3)...
    std(Air.Duration.Duration_Up_Units_Quantile_Segment_Spike_Means.Quant3_Seg3)...
    size(Air.Duration.Duration_Up_Units_Quantile_Segment_Spike_Means,1)];

Summary_data.Up_Quant_Z_Spike_Seg(12,1:3) = [mean(Air.Duration.Duration_Up_Units_Quantile_Segment_Spike_Means.Quant3_Seg4)...
    std(Air.Duration.Duration_Up_Units_Quantile_Segment_Spike_Means.Quant3_Seg4)...
    size(Air.Duration.Duration_Up_Units_Quantile_Segment_Spike_Means,1)];



Summary_data.Up_Quant_Z_Spike_Seg(13,1:3) = [mean(Air.Duration.Duration_Up_Units_Quantile_Segment_Spike_Means.Quant4_Seg1)...
    std(Air.Duration.Duration_Up_Units_Quantile_Segment_Spike_Means.Quant4_Seg1)...
    size(Air.Duration.Duration_Up_Units_Quantile_Segment_Spike_Means,1)];

Summary_data.Up_Quant_Z_Spike_Seg(14,1:3) = [mean(Air.Duration.Duration_Up_Units_Quantile_Segment_Spike_Means.Quant4_Seg2)...
    std(Air.Duration.Duration_Up_Units_Quantile_Segment_Spike_Means.Quant4_Seg2)...
    size(Air.Duration.Duration_Up_Units_Quantile_Segment_Spike_Means,1)];

Summary_data.Up_Quant_Z_Spike_Seg(15,1:3) = [mean(Air.Duration.Duration_Up_Units_Quantile_Segment_Spike_Means.Quant4_Seg3)...
    std(Air.Duration.Duration_Up_Units_Quantile_Segment_Spike_Means.Quant4_Seg3)...
    size(Air.Duration.Duration_Up_Units_Quantile_Segment_Spike_Means,1)];

Summary_data.Up_Quant_Z_Spike_Seg(16,1:3) = [mean(Air.Duration.Duration_Up_Units_Quantile_Segment_Spike_Means.Quant4_Seg4)...
    std(Air.Duration.Duration_Up_Units_Quantile_Segment_Spike_Means.Quant4_Seg4)...
    size(Air.Duration.Duration_Up_Units_Quantile_Segment_Spike_Means,1)];


%% Quantile Z Down Modulated Segment: Spike LPs
Summary_data.Down_Quant_Z_Spike_Seg(1,1:3) = [mean(Air.Duration.Duration_Down_Units_Quantile_Segment_Spike_Means.Quant1_Seg1)...
    std(Air.Duration.Duration_Down_Units_Quantile_Segment_Spike_Means.Quant1_Seg1)...
    size(Air.Duration.Duration_Down_Units_Quantile_Segment_Spike_Means,1)];

Summary_data.Down_Quant_Z_Spike_Seg(2,1:3) = [mean(Air.Duration.Duration_Down_Units_Quantile_Segment_Spike_Means.Quant1_Seg2)...
    std(Air.Duration.Duration_Down_Units_Quantile_Segment_Spike_Means.Quant1_Seg2)...
    size(Air.Duration.Duration_Down_Units_Quantile_Segment_Spike_Means,1)];

Summary_data.Down_Quant_Z_Spike_Seg(3,1:3) = [mean(Air.Duration.Duration_Down_Units_Quantile_Segment_Spike_Means.Quant1_Seg3)...
    std(Air.Duration.Duration_Down_Units_Quantile_Segment_Spike_Means.Quant1_Seg3)...
    size(Air.Duration.Duration_Down_Units_Quantile_Segment_Spike_Means,1)];

Summary_data.Down_Quant_Z_Spike_Seg(4,1:3) = [mean(Air.Duration.Duration_Down_Units_Quantile_Segment_Spike_Means.Quant1_Seg4)...
    std(Air.Duration.Duration_Down_Units_Quantile_Segment_Spike_Means.Quant1_Seg4)...
    size(Air.Duration.Duration_Down_Units_Quantile_Segment_Spike_Means,1)];



Summary_data.Down_Quant_Z_Spike_Seg(5,1:3) = [mean(Air.Duration.Duration_Down_Units_Quantile_Segment_Spike_Means.Quant2_Seg1)...
    std(Air.Duration.Duration_Down_Units_Quantile_Segment_Spike_Means.Quant2_Seg1)...
    size(Air.Duration.Duration_Down_Units_Quantile_Segment_Spike_Means,1)];

Summary_data.Down_Quant_Z_Spike_Seg(6,1:3) = [mean(Air.Duration.Duration_Down_Units_Quantile_Segment_Spike_Means.Quant2_Seg2)...
    std(Air.Duration.Duration_Down_Units_Quantile_Segment_Spike_Means.Quant2_Seg2)...
    size(Air.Duration.Duration_Down_Units_Quantile_Segment_Spike_Means,1)];

Summary_data.Down_Quant_Z_Spike_Seg(7,1:3) = [mean(Air.Duration.Duration_Down_Units_Quantile_Segment_Spike_Means.Quant2_Seg3)...
    std(Air.Duration.Duration_Down_Units_Quantile_Segment_Spike_Means.Quant2_Seg3)...
    size(Air.Duration.Duration_Down_Units_Quantile_Segment_Spike_Means,1)];

Summary_data.Down_Quant_Z_Spike_Seg(8,1:3) = [mean(Air.Duration.Duration_Down_Units_Quantile_Segment_Spike_Means.Quant2_Seg4)...
    std(Air.Duration.Duration_Down_Units_Quantile_Segment_Spike_Means.Quant2_Seg4)...
    size(Air.Duration.Duration_Down_Units_Quantile_Segment_Spike_Means,1)];



Summary_data.Down_Quant_Z_Spike_Seg(9,1:3) = [mean(Air.Duration.Duration_Down_Units_Quantile_Segment_Spike_Means.Quant3_Seg1)...
    std(Air.Duration.Duration_Down_Units_Quantile_Segment_Spike_Means.Quant3_Seg1)...
    size(Air.Duration.Duration_Down_Units_Quantile_Segment_Spike_Means,1)];

Summary_data.Down_Quant_Z_Spike_Seg(10,1:3) = [mean(Air.Duration.Duration_Down_Units_Quantile_Segment_Spike_Means.Quant3_Seg2)...
    std(Air.Duration.Duration_Down_Units_Quantile_Segment_Spike_Means.Quant3_Seg2)...
    size(Air.Duration.Duration_Down_Units_Quantile_Segment_Spike_Means,1)];

Summary_data.Down_Quant_Z_Spike_Seg(11,1:3) = [mean(Air.Duration.Duration_Down_Units_Quantile_Segment_Spike_Means.Quant3_Seg3)...
    std(Air.Duration.Duration_Down_Units_Quantile_Segment_Spike_Means.Quant3_Seg3)...
    size(Air.Duration.Duration_Down_Units_Quantile_Segment_Spike_Means,1)];

Summary_data.Down_Quant_Z_Spike_Seg(12,1:3) = [mean(Air.Duration.Duration_Down_Units_Quantile_Segment_Spike_Means.Quant3_Seg4)...
    std(Air.Duration.Duration_Down_Units_Quantile_Segment_Spike_Means.Quant3_Seg4)...
    size(Air.Duration.Duration_Down_Units_Quantile_Segment_Spike_Means,1)];



Summary_data.Down_Quant_Z_Spike_Seg(13,1:3) = [mean(Air.Duration.Duration_Down_Units_Quantile_Segment_Spike_Means.Quant4_Seg1)...
    std(Air.Duration.Duration_Down_Units_Quantile_Segment_Spike_Means.Quant4_Seg1)...
    size(Air.Duration.Duration_Down_Units_Quantile_Segment_Spike_Means,1)];

Summary_data.Down_Quant_Z_Spike_Seg(14,1:3) = [mean(Air.Duration.Duration_Down_Units_Quantile_Segment_Spike_Means.Quant4_Seg2)...
    std(Air.Duration.Duration_Down_Units_Quantile_Segment_Spike_Means.Quant4_Seg2)...
    size(Air.Duration.Duration_Down_Units_Quantile_Segment_Spike_Means,1)];

Summary_data.Down_Quant_Z_Spike_Seg(15,1:3) = [mean(Air.Duration.Duration_Down_Units_Quantile_Segment_Spike_Means.Quant4_Seg3)...
    std(Air.Duration.Duration_Down_Units_Quantile_Segment_Spike_Means.Quant4_Seg3)...
    size(Air.Duration.Duration_Down_Units_Quantile_Segment_Spike_Means,1)];

Summary_data.Down_Quant_Z_Spike_Seg(16,1:3) = [mean(Air.Duration.Duration_Down_Units_Quantile_Segment_Spike_Means.Quant4_Seg4)...
    std(Air.Duration.Duration_Down_Units_Quantile_Segment_Spike_Means.Quant4_Seg4)...
    size(Air.Duration.Duration_Down_Units_Quantile_Segment_Spike_Means,1)];





%% Quantile Z Up Modulated Segment: All LPs
Summary_data.Up_Quant_Z_All_Seg(1,1:3) = [mean(Air.Duration.Duration_Up_Units_Quantile_Segment_Means.Quant1_Seg1)...
    std(Air.Duration.Duration_Up_Units_Quantile_Segment_Means.Quant1_Seg1)...
    size(Air.Duration.Duration_Up_Units_Quantile_Segment_Means,1)];

Summary_data.Up_Quant_Z_All_Seg(2,1:3) = [mean(Air.Duration.Duration_Up_Units_Quantile_Segment_Means.Quant1_Seg2)...
    std(Air.Duration.Duration_Up_Units_Quantile_Segment_Means.Quant1_Seg2)...
    size(Air.Duration.Duration_Up_Units_Quantile_Segment_Means,1)];

Summary_data.Up_Quant_Z_All_Seg(3,1:3) = [mean(Air.Duration.Duration_Up_Units_Quantile_Segment_Means.Quant1_Seg3)...
    std(Air.Duration.Duration_Up_Units_Quantile_Segment_Means.Quant1_Seg3)...
    size(Air.Duration.Duration_Up_Units_Quantile_Segment_Means,1)];

Summary_data.Up_Quant_Z_All_Seg(4,1:3) = [mean(Air.Duration.Duration_Up_Units_Quantile_Segment_Means.Quant1_Seg4)...
    std(Air.Duration.Duration_Up_Units_Quantile_Segment_Means.Quant1_Seg4)...
    size(Air.Duration.Duration_Up_Units_Quantile_Segment_Means,1)];



Summary_data.Up_Quant_Z_All_Seg(5,1:3) = [mean(Air.Duration.Duration_Up_Units_Quantile_Segment_Means.Quant2_Seg1)...
    std(Air.Duration.Duration_Up_Units_Quantile_Segment_Means.Quant2_Seg1)...
    size(Air.Duration.Duration_Up_Units_Quantile_Segment_Means,1)];

Summary_data.Up_Quant_Z_All_Seg(6,1:3) = [mean(Air.Duration.Duration_Up_Units_Quantile_Segment_Means.Quant2_Seg2)...
    std(Air.Duration.Duration_Up_Units_Quantile_Segment_Means.Quant2_Seg2)...
    size(Air.Duration.Duration_Up_Units_Quantile_Segment_Means,1)];

Summary_data.Up_Quant_Z_All_Seg(7,1:3) = [mean(Air.Duration.Duration_Up_Units_Quantile_Segment_Means.Quant2_Seg3)...
    std(Air.Duration.Duration_Up_Units_Quantile_Segment_Means.Quant2_Seg3)...
    size(Air.Duration.Duration_Up_Units_Quantile_Segment_Means,1)];

Summary_data.Up_Quant_Z_All_Seg(8,1:3) = [mean(Air.Duration.Duration_Up_Units_Quantile_Segment_Means.Quant2_Seg4)...
    std(Air.Duration.Duration_Up_Units_Quantile_Segment_Means.Quant2_Seg4)...
    size(Air.Duration.Duration_Up_Units_Quantile_Segment_Means,1)];



Summary_data.Up_Quant_Z_All_Seg(9,1:3) = [mean(Air.Duration.Duration_Up_Units_Quantile_Segment_Means.Quant3_Seg1)...
    std(Air.Duration.Duration_Up_Units_Quantile_Segment_Means.Quant3_Seg1)...
    size(Air.Duration.Duration_Up_Units_Quantile_Segment_Means,1)];

Summary_data.Up_Quant_Z_All_Seg(10,1:3) = [mean(Air.Duration.Duration_Up_Units_Quantile_Segment_Means.Quant3_Seg2)...
    std(Air.Duration.Duration_Up_Units_Quantile_Segment_Means.Quant3_Seg2)...
    size(Air.Duration.Duration_Up_Units_Quantile_Segment_Means,1)];

Summary_data.Up_Quant_Z_All_Seg(11,1:3) = [mean(Air.Duration.Duration_Up_Units_Quantile_Segment_Means.Quant3_Seg3)...
    std(Air.Duration.Duration_Up_Units_Quantile_Segment_Means.Quant3_Seg3)...
    size(Air.Duration.Duration_Up_Units_Quantile_Segment_Means,1)];

Summary_data.Up_Quant_Z_All_Seg(12,1:3) = [mean(Air.Duration.Duration_Up_Units_Quantile_Segment_Means.Quant3_Seg4)...
    std(Air.Duration.Duration_Up_Units_Quantile_Segment_Means.Quant3_Seg4)...
    size(Air.Duration.Duration_Up_Units_Quantile_Segment_Means,1)];



Summary_data.Up_Quant_Z_All_Seg(13,1:3) = [mean(Air.Duration.Duration_Up_Units_Quantile_Segment_Means.Quant4_Seg1)...
    std(Air.Duration.Duration_Up_Units_Quantile_Segment_Means.Quant4_Seg1)...
    size(Air.Duration.Duration_Up_Units_Quantile_Segment_Means,1)];

Summary_data.Up_Quant_Z_All_Seg(14,1:3) = [mean(Air.Duration.Duration_Up_Units_Quantile_Segment_Means.Quant4_Seg2)...
    std(Air.Duration.Duration_Up_Units_Quantile_Segment_Means.Quant4_Seg2)...
    size(Air.Duration.Duration_Up_Units_Quantile_Segment_Means,1)];

Summary_data.Up_Quant_Z_All_Seg(15,1:3) = [mean(Air.Duration.Duration_Up_Units_Quantile_Segment_Means.Quant4_Seg3)...
    std(Air.Duration.Duration_Up_Units_Quantile_Segment_Means.Quant4_Seg3)...
    size(Air.Duration.Duration_Up_Units_Quantile_Segment_Means,1)];

Summary_data.Up_Quant_Z_All_Seg(16,1:3) = [mean(Air.Duration.Duration_Up_Units_Quantile_Segment_Means.Quant4_Seg4)...
    std(Air.Duration.Duration_Up_Units_Quantile_Segment_Means.Quant4_Seg4)...
    size(Air.Duration.Duration_Up_Units_Quantile_Segment_Means,1)];


%% Quantile Z Down Modulated Segment: All LPs
Summary_data.Down_Quant_Z_All_Seg(1,1:3) = [mean(Air.Duration.Duration_Down_Units_Quantile_Segment_Means.Quant1_Seg1)...
    std(Air.Duration.Duration_Down_Units_Quantile_Segment_Means.Quant1_Seg1)...
    size(Air.Duration.Duration_Down_Units_Quantile_Segment_Means,1)];

Summary_data.Down_Quant_Z_All_Seg(2,1:3) = [mean(Air.Duration.Duration_Down_Units_Quantile_Segment_Means.Quant1_Seg2)...
    std(Air.Duration.Duration_Down_Units_Quantile_Segment_Means.Quant1_Seg2)...
    size(Air.Duration.Duration_Down_Units_Quantile_Segment_Means,1)];

Summary_data.Down_Quant_Z_All_Seg(3,1:3) = [mean(Air.Duration.Duration_Down_Units_Quantile_Segment_Means.Quant1_Seg3)...
    std(Air.Duration.Duration_Down_Units_Quantile_Segment_Means.Quant1_Seg3)...
    size(Air.Duration.Duration_Down_Units_Quantile_Segment_Means,1)];

Summary_data.Down_Quant_Z_All_Seg(4,1:3) = [mean(Air.Duration.Duration_Down_Units_Quantile_Segment_Means.Quant1_Seg4)...
    std(Air.Duration.Duration_Down_Units_Quantile_Segment_Means.Quant1_Seg4)...
    size(Air.Duration.Duration_Down_Units_Quantile_Segment_Means,1)];



Summary_data.Down_Quant_Z_All_Seg(5,1:3) = [mean(Air.Duration.Duration_Down_Units_Quantile_Segment_Means.Quant2_Seg1)...
    std(Air.Duration.Duration_Down_Units_Quantile_Segment_Means.Quant2_Seg1)...
    size(Air.Duration.Duration_Down_Units_Quantile_Segment_Means,1)];

Summary_data.Down_Quant_Z_All_Seg(6,1:3) = [mean(Air.Duration.Duration_Down_Units_Quantile_Segment_Means.Quant2_Seg2)...
    std(Air.Duration.Duration_Down_Units_Quantile_Segment_Means.Quant2_Seg2)...
    size(Air.Duration.Duration_Down_Units_Quantile_Segment_Means,1)];

Summary_data.Down_Quant_Z_All_Seg(7,1:3) = [mean(Air.Duration.Duration_Down_Units_Quantile_Segment_Means.Quant2_Seg3)...
    std(Air.Duration.Duration_Down_Units_Quantile_Segment_Means.Quant2_Seg3)...
    size(Air.Duration.Duration_Down_Units_Quantile_Segment_Means,1)];

Summary_data.Down_Quant_Z_All_Seg(8,1:3) = [mean(Air.Duration.Duration_Down_Units_Quantile_Segment_Means.Quant2_Seg4)...
    std(Air.Duration.Duration_Down_Units_Quantile_Segment_Means.Quant2_Seg4)...
    size(Air.Duration.Duration_Down_Units_Quantile_Segment_Means,1)];



Summary_data.Down_Quant_Z_All_Seg(9,1:3) = [mean(Air.Duration.Duration_Down_Units_Quantile_Segment_Means.Quant3_Seg1)...
    std(Air.Duration.Duration_Down_Units_Quantile_Segment_Means.Quant3_Seg1)...
    size(Air.Duration.Duration_Down_Units_Quantile_Segment_Means,1)];

Summary_data.Down_Quant_Z_All_Seg(10,1:3) = [mean(Air.Duration.Duration_Down_Units_Quantile_Segment_Means.Quant3_Seg2)...
    std(Air.Duration.Duration_Down_Units_Quantile_Segment_Means.Quant3_Seg2)...
    size(Air.Duration.Duration_Down_Units_Quantile_Segment_Means,1)];

Summary_data.Down_Quant_Z_All_Seg(11,1:3) = [mean(Air.Duration.Duration_Down_Units_Quantile_Segment_Means.Quant3_Seg3)...
    std(Air.Duration.Duration_Down_Units_Quantile_Segment_Means.Quant3_Seg3)...
    size(Air.Duration.Duration_Down_Units_Quantile_Segment_Means,1)];

Summary_data.Down_Quant_Z_All_Seg(12,1:3) = [mean(Air.Duration.Duration_Down_Units_Quantile_Segment_Means.Quant3_Seg4)...
    std(Air.Duration.Duration_Down_Units_Quantile_Segment_Means.Quant3_Seg4)...
    size(Air.Duration.Duration_Down_Units_Quantile_Segment_Means,1)];



Summary_data.Down_Quant_Z_All_Seg(13,1:3) = [mean(Air.Duration.Duration_Down_Units_Quantile_Segment_Means.Quant4_Seg1)...
    std(Air.Duration.Duration_Down_Units_Quantile_Segment_Means.Quant4_Seg1)...
    size(Air.Duration.Duration_Down_Units_Quantile_Segment_Means,1)];

Summary_data.Down_Quant_Z_All_Seg(14,1:3) = [mean(Air.Duration.Duration_Down_Units_Quantile_Segment_Means.Quant4_Seg2)...
    std(Air.Duration.Duration_Down_Units_Quantile_Segment_Means.Quant4_Seg2)...
    size(Air.Duration.Duration_Down_Units_Quantile_Segment_Means,1)];

Summary_data.Down_Quant_Z_All_Seg(15,1:3) = [mean(Air.Duration.Duration_Down_Units_Quantile_Segment_Means.Quant4_Seg3)...
    std(Air.Duration.Duration_Down_Units_Quantile_Segment_Means.Quant4_Seg3)...
    size(Air.Duration.Duration_Down_Units_Quantile_Segment_Means,1)];

Summary_data.Down_Quant_Z_All_Seg(16,1:3) = [mean(Air.Duration.Duration_Down_Units_Quantile_Segment_Means.Quant4_Seg4)...
    std(Air.Duration.Duration_Down_Units_Quantile_Segment_Means.Quant4_Seg4)...
    size(Air.Duration.Duration_Down_Units_Quantile_Segment_Means,1)];



























%% Quantile Z Up Modulated  Segment : Spike LPs
Summary_data.Up_Quant_Z_Spike_Seg(1,4:6) = [mean(CIE.Duration.Duration_Up_Units_Quantile_Segment_Spike_Means.Quant1_Seg1)...
    std(CIE.Duration.Duration_Up_Units_Quantile_Segment_Spike_Means.Quant1_Seg1)...
    size(CIE.Duration.Duration_Up_Units_Quantile_Segment_Spike_Means,1)];

Summary_data.Up_Quant_Z_Spike_Seg(2,4:6) = [mean(CIE.Duration.Duration_Up_Units_Quantile_Segment_Spike_Means.Quant1_Seg2)...
    std(CIE.Duration.Duration_Up_Units_Quantile_Segment_Spike_Means.Quant1_Seg2)...
    size(CIE.Duration.Duration_Up_Units_Quantile_Segment_Spike_Means,1)];

Summary_data.Up_Quant_Z_Spike_Seg(3,4:6) = [mean(CIE.Duration.Duration_Up_Units_Quantile_Segment_Spike_Means.Quant1_Seg3)...
    std(CIE.Duration.Duration_Up_Units_Quantile_Segment_Spike_Means.Quant1_Seg3)...
    size(CIE.Duration.Duration_Up_Units_Quantile_Segment_Spike_Means,1)];

Summary_data.Up_Quant_Z_Spike_Seg(4,4:6) = [mean(CIE.Duration.Duration_Up_Units_Quantile_Segment_Spike_Means.Quant1_Seg4)...
    std(CIE.Duration.Duration_Up_Units_Quantile_Segment_Spike_Means.Quant1_Seg4)...
    size(CIE.Duration.Duration_Up_Units_Quantile_Segment_Spike_Means,1)];



Summary_data.Up_Quant_Z_Spike_Seg(5,4:6) = [mean(CIE.Duration.Duration_Up_Units_Quantile_Segment_Spike_Means.Quant2_Seg1)...
    std(CIE.Duration.Duration_Up_Units_Quantile_Segment_Spike_Means.Quant2_Seg1)...
    size(CIE.Duration.Duration_Up_Units_Quantile_Segment_Spike_Means,1)];

Summary_data.Up_Quant_Z_Spike_Seg(6,4:6) = [mean(CIE.Duration.Duration_Up_Units_Quantile_Segment_Spike_Means.Quant2_Seg2)...
    std(CIE.Duration.Duration_Up_Units_Quantile_Segment_Spike_Means.Quant2_Seg2)...
    size(CIE.Duration.Duration_Up_Units_Quantile_Segment_Spike_Means,1)];

Summary_data.Up_Quant_Z_Spike_Seg(7,4:6) = [mean(CIE.Duration.Duration_Up_Units_Quantile_Segment_Spike_Means.Quant2_Seg3)...
    std(CIE.Duration.Duration_Up_Units_Quantile_Segment_Spike_Means.Quant2_Seg3)...
    size(CIE.Duration.Duration_Up_Units_Quantile_Segment_Spike_Means,1)];

Summary_data.Up_Quant_Z_Spike_Seg(8,4:6) = [mean(CIE.Duration.Duration_Up_Units_Quantile_Segment_Spike_Means.Quant2_Seg4)...
    std(CIE.Duration.Duration_Up_Units_Quantile_Segment_Spike_Means.Quant2_Seg4)...
    size(CIE.Duration.Duration_Up_Units_Quantile_Segment_Spike_Means,1)];



Summary_data.Up_Quant_Z_Spike_Seg(9,4:6) = [mean(CIE.Duration.Duration_Up_Units_Quantile_Segment_Spike_Means.Quant3_Seg1)...
    std(CIE.Duration.Duration_Up_Units_Quantile_Segment_Spike_Means.Quant3_Seg1)...
    size(CIE.Duration.Duration_Up_Units_Quantile_Segment_Spike_Means,1)];

Summary_data.Up_Quant_Z_Spike_Seg(10,4:6) = [mean(CIE.Duration.Duration_Up_Units_Quantile_Segment_Spike_Means.Quant3_Seg2)...
    std(CIE.Duration.Duration_Up_Units_Quantile_Segment_Spike_Means.Quant3_Seg2)...
    size(CIE.Duration.Duration_Up_Units_Quantile_Segment_Spike_Means,1)];

Summary_data.Up_Quant_Z_Spike_Seg(11,4:6) = [mean(CIE.Duration.Duration_Up_Units_Quantile_Segment_Spike_Means.Quant3_Seg3)...
    std(CIE.Duration.Duration_Up_Units_Quantile_Segment_Spike_Means.Quant3_Seg3)...
    size(CIE.Duration.Duration_Up_Units_Quantile_Segment_Spike_Means,1)];

Summary_data.Up_Quant_Z_Spike_Seg(12,4:6) = [mean(CIE.Duration.Duration_Up_Units_Quantile_Segment_Spike_Means.Quant3_Seg4)...
    std(CIE.Duration.Duration_Up_Units_Quantile_Segment_Spike_Means.Quant3_Seg4)...
    size(CIE.Duration.Duration_Up_Units_Quantile_Segment_Spike_Means,1)];



Summary_data.Up_Quant_Z_Spike_Seg(13,4:6) = [mean(CIE.Duration.Duration_Up_Units_Quantile_Segment_Spike_Means.Quant4_Seg1)...
    std(CIE.Duration.Duration_Up_Units_Quantile_Segment_Spike_Means.Quant4_Seg1)...
    size(CIE.Duration.Duration_Up_Units_Quantile_Segment_Spike_Means,1)];

Summary_data.Up_Quant_Z_Spike_Seg(14,4:6) = [mean(CIE.Duration.Duration_Up_Units_Quantile_Segment_Spike_Means.Quant4_Seg2)...
    std(CIE.Duration.Duration_Up_Units_Quantile_Segment_Spike_Means.Quant4_Seg2)...
    size(CIE.Duration.Duration_Up_Units_Quantile_Segment_Spike_Means,1)];

Summary_data.Up_Quant_Z_Spike_Seg(15,4:6) = [mean(CIE.Duration.Duration_Up_Units_Quantile_Segment_Spike_Means.Quant4_Seg3)...
    std(CIE.Duration.Duration_Up_Units_Quantile_Segment_Spike_Means.Quant4_Seg3)...
    size(CIE.Duration.Duration_Up_Units_Quantile_Segment_Spike_Means,1)];

Summary_data.Up_Quant_Z_Spike_Seg(16,4:6) = [mean(CIE.Duration.Duration_Up_Units_Quantile_Segment_Spike_Means.Quant4_Seg4)...
    std(CIE.Duration.Duration_Up_Units_Quantile_Segment_Spike_Means.Quant4_Seg4)...
    size(CIE.Duration.Duration_Up_Units_Quantile_Segment_Spike_Means,1)];


%% Quantile Z Down Modulated Segment: Spike LPs
Summary_data.Down_Quant_Z_Spike_Seg(1,4:6) = [mean(CIE.Duration.Duration_Down_Units_Quantile_Segment_Spike_Means.Quant1_Seg1)...
    std(CIE.Duration.Duration_Down_Units_Quantile_Segment_Spike_Means.Quant1_Seg1)...
    size(CIE.Duration.Duration_Down_Units_Quantile_Segment_Spike_Means,1)];

Summary_data.Down_Quant_Z_Spike_Seg(2,4:6) = [mean(CIE.Duration.Duration_Down_Units_Quantile_Segment_Spike_Means.Quant1_Seg2)...
    std(CIE.Duration.Duration_Down_Units_Quantile_Segment_Spike_Means.Quant1_Seg2)...
    size(CIE.Duration.Duration_Down_Units_Quantile_Segment_Spike_Means,1)];

Summary_data.Down_Quant_Z_Spike_Seg(3,4:6) = [mean(CIE.Duration.Duration_Down_Units_Quantile_Segment_Spike_Means.Quant1_Seg3)...
    std(CIE.Duration.Duration_Down_Units_Quantile_Segment_Spike_Means.Quant1_Seg3)...
    size(CIE.Duration.Duration_Down_Units_Quantile_Segment_Spike_Means,1)];

Summary_data.Down_Quant_Z_Spike_Seg(4,4:6) = [mean(CIE.Duration.Duration_Down_Units_Quantile_Segment_Spike_Means.Quant1_Seg4)...
    std(CIE.Duration.Duration_Down_Units_Quantile_Segment_Spike_Means.Quant1_Seg4)...
    size(CIE.Duration.Duration_Down_Units_Quantile_Segment_Spike_Means,1)];



Summary_data.Down_Quant_Z_Spike_Seg(5,4:6) = [mean(CIE.Duration.Duration_Down_Units_Quantile_Segment_Spike_Means.Quant2_Seg1)...
    std(CIE.Duration.Duration_Down_Units_Quantile_Segment_Spike_Means.Quant2_Seg1)...
    size(CIE.Duration.Duration_Down_Units_Quantile_Segment_Spike_Means,1)];

Summary_data.Down_Quant_Z_Spike_Seg(6,4:6) = [mean(CIE.Duration.Duration_Down_Units_Quantile_Segment_Spike_Means.Quant2_Seg2)...
    std(CIE.Duration.Duration_Down_Units_Quantile_Segment_Spike_Means.Quant2_Seg2)...
    size(CIE.Duration.Duration_Down_Units_Quantile_Segment_Spike_Means,1)];

Summary_data.Down_Quant_Z_Spike_Seg(7,4:6) = [mean(CIE.Duration.Duration_Down_Units_Quantile_Segment_Spike_Means.Quant2_Seg3)...
    std(CIE.Duration.Duration_Down_Units_Quantile_Segment_Spike_Means.Quant2_Seg3)...
    size(CIE.Duration.Duration_Down_Units_Quantile_Segment_Spike_Means,1)];

Summary_data.Down_Quant_Z_Spike_Seg(8,4:6) = [mean(CIE.Duration.Duration_Down_Units_Quantile_Segment_Spike_Means.Quant2_Seg4)...
    std(CIE.Duration.Duration_Down_Units_Quantile_Segment_Spike_Means.Quant2_Seg4)...
    size(CIE.Duration.Duration_Down_Units_Quantile_Segment_Spike_Means,1)];



Summary_data.Down_Quant_Z_Spike_Seg(9,4:6) = [mean(CIE.Duration.Duration_Down_Units_Quantile_Segment_Spike_Means.Quant3_Seg1)...
    std(CIE.Duration.Duration_Down_Units_Quantile_Segment_Spike_Means.Quant3_Seg1)...
    size(CIE.Duration.Duration_Down_Units_Quantile_Segment_Spike_Means,1)];

Summary_data.Down_Quant_Z_Spike_Seg(10,4:6) = [mean(CIE.Duration.Duration_Down_Units_Quantile_Segment_Spike_Means.Quant3_Seg2)...
    std(CIE.Duration.Duration_Down_Units_Quantile_Segment_Spike_Means.Quant3_Seg2)...
    size(CIE.Duration.Duration_Down_Units_Quantile_Segment_Spike_Means,1)];

Summary_data.Down_Quant_Z_Spike_Seg(11,4:6) = [mean(CIE.Duration.Duration_Down_Units_Quantile_Segment_Spike_Means.Quant3_Seg3)...
    std(CIE.Duration.Duration_Down_Units_Quantile_Segment_Spike_Means.Quant3_Seg3)...
    size(CIE.Duration.Duration_Down_Units_Quantile_Segment_Spike_Means,1)];

Summary_data.Down_Quant_Z_Spike_Seg(12,4:6) = [mean(CIE.Duration.Duration_Down_Units_Quantile_Segment_Spike_Means.Quant3_Seg4)...
    std(CIE.Duration.Duration_Down_Units_Quantile_Segment_Spike_Means.Quant3_Seg4)...
    size(CIE.Duration.Duration_Down_Units_Quantile_Segment_Spike_Means,1)];



Summary_data.Down_Quant_Z_Spike_Seg(13,4:6) = [mean(CIE.Duration.Duration_Down_Units_Quantile_Segment_Spike_Means.Quant4_Seg1)...
    std(CIE.Duration.Duration_Down_Units_Quantile_Segment_Spike_Means.Quant4_Seg1)...
    size(CIE.Duration.Duration_Down_Units_Quantile_Segment_Spike_Means,1)];

Summary_data.Down_Quant_Z_Spike_Seg(14,4:6) = [mean(CIE.Duration.Duration_Down_Units_Quantile_Segment_Spike_Means.Quant4_Seg2)...
    std(CIE.Duration.Duration_Down_Units_Quantile_Segment_Spike_Means.Quant4_Seg2)...
    size(CIE.Duration.Duration_Down_Units_Quantile_Segment_Spike_Means,1)];

Summary_data.Down_Quant_Z_Spike_Seg(15,4:6) = [mean(CIE.Duration.Duration_Down_Units_Quantile_Segment_Spike_Means.Quant4_Seg3)...
    std(CIE.Duration.Duration_Down_Units_Quantile_Segment_Spike_Means.Quant4_Seg3)...
    size(CIE.Duration.Duration_Down_Units_Quantile_Segment_Spike_Means,1)];

Summary_data.Down_Quant_Z_Spike_Seg(16,4:6) = [mean(CIE.Duration.Duration_Down_Units_Quantile_Segment_Spike_Means.Quant4_Seg4)...
    std(CIE.Duration.Duration_Down_Units_Quantile_Segment_Spike_Means.Quant4_Seg4)...
    size(CIE.Duration.Duration_Down_Units_Quantile_Segment_Spike_Means,1)];





%% Quantile Z Up Modulated Segment: All LPs
Summary_data.Up_Quant_Z_All_Seg(1,4:6) = [mean(CIE.Duration.Duration_Up_Units_Quantile_Segment_Means.Quant1_Seg1)...
    std(CIE.Duration.Duration_Up_Units_Quantile_Segment_Means.Quant1_Seg1)...
    size(CIE.Duration.Duration_Up_Units_Quantile_Segment_Means,1)];

Summary_data.Up_Quant_Z_All_Seg(2,4:6) = [mean(CIE.Duration.Duration_Up_Units_Quantile_Segment_Means.Quant1_Seg2)...
    std(CIE.Duration.Duration_Up_Units_Quantile_Segment_Means.Quant1_Seg2)...
    size(CIE.Duration.Duration_Up_Units_Quantile_Segment_Means,1)];

Summary_data.Up_Quant_Z_All_Seg(3,4:6) = [mean(CIE.Duration.Duration_Up_Units_Quantile_Segment_Means.Quant1_Seg3)...
    std(CIE.Duration.Duration_Up_Units_Quantile_Segment_Means.Quant1_Seg3)...
    size(CIE.Duration.Duration_Up_Units_Quantile_Segment_Means,1)];

Summary_data.Up_Quant_Z_All_Seg(4,4:6) = [mean(CIE.Duration.Duration_Up_Units_Quantile_Segment_Means.Quant1_Seg4)...
    std(CIE.Duration.Duration_Up_Units_Quantile_Segment_Means.Quant1_Seg4)...
    size(CIE.Duration.Duration_Up_Units_Quantile_Segment_Means,1)];



Summary_data.Up_Quant_Z_All_Seg(5,4:6) = [mean(CIE.Duration.Duration_Up_Units_Quantile_Segment_Means.Quant2_Seg1)...
    std(CIE.Duration.Duration_Up_Units_Quantile_Segment_Means.Quant2_Seg1)...
    size(CIE.Duration.Duration_Up_Units_Quantile_Segment_Means,1)];

Summary_data.Up_Quant_Z_All_Seg(6,4:6) = [mean(CIE.Duration.Duration_Up_Units_Quantile_Segment_Means.Quant2_Seg2)...
    std(CIE.Duration.Duration_Up_Units_Quantile_Segment_Means.Quant2_Seg2)...
    size(CIE.Duration.Duration_Up_Units_Quantile_Segment_Means,1)];

Summary_data.Up_Quant_Z_All_Seg(7,4:6) = [mean(CIE.Duration.Duration_Up_Units_Quantile_Segment_Means.Quant2_Seg3)...
    std(CIE.Duration.Duration_Up_Units_Quantile_Segment_Means.Quant2_Seg3)...
    size(CIE.Duration.Duration_Up_Units_Quantile_Segment_Means,1)];

Summary_data.Up_Quant_Z_All_Seg(8,4:6) = [mean(CIE.Duration.Duration_Up_Units_Quantile_Segment_Means.Quant2_Seg4)...
    std(CIE.Duration.Duration_Up_Units_Quantile_Segment_Means.Quant2_Seg4)...
    size(CIE.Duration.Duration_Up_Units_Quantile_Segment_Means,1)];



Summary_data.Up_Quant_Z_All_Seg(9,4:6) = [mean(CIE.Duration.Duration_Up_Units_Quantile_Segment_Means.Quant3_Seg1)...
    std(CIE.Duration.Duration_Up_Units_Quantile_Segment_Means.Quant3_Seg1)...
    size(CIE.Duration.Duration_Up_Units_Quantile_Segment_Means,1)];

Summary_data.Up_Quant_Z_All_Seg(10,4:6) = [mean(CIE.Duration.Duration_Up_Units_Quantile_Segment_Means.Quant3_Seg2)...
    std(CIE.Duration.Duration_Up_Units_Quantile_Segment_Means.Quant3_Seg2)...
    size(CIE.Duration.Duration_Up_Units_Quantile_Segment_Means,1)];

Summary_data.Up_Quant_Z_All_Seg(11,4:6) = [mean(CIE.Duration.Duration_Up_Units_Quantile_Segment_Means.Quant3_Seg3)...
    std(CIE.Duration.Duration_Up_Units_Quantile_Segment_Means.Quant3_Seg3)...
    size(CIE.Duration.Duration_Up_Units_Quantile_Segment_Means,1)];

Summary_data.Up_Quant_Z_All_Seg(12,4:6) = [mean(CIE.Duration.Duration_Up_Units_Quantile_Segment_Means.Quant3_Seg4)...
    std(CIE.Duration.Duration_Up_Units_Quantile_Segment_Means.Quant3_Seg4)...
    size(CIE.Duration.Duration_Up_Units_Quantile_Segment_Means,1)];



Summary_data.Up_Quant_Z_All_Seg(13,4:6) = [mean(CIE.Duration.Duration_Up_Units_Quantile_Segment_Means.Quant4_Seg1)...
    std(CIE.Duration.Duration_Up_Units_Quantile_Segment_Means.Quant4_Seg1)...
    size(CIE.Duration.Duration_Up_Units_Quantile_Segment_Means,1)];

Summary_data.Up_Quant_Z_All_Seg(14,4:6) = [mean(CIE.Duration.Duration_Up_Units_Quantile_Segment_Means.Quant4_Seg2)...
    std(CIE.Duration.Duration_Up_Units_Quantile_Segment_Means.Quant4_Seg2)...
    size(CIE.Duration.Duration_Up_Units_Quantile_Segment_Means,1)];

Summary_data.Up_Quant_Z_All_Seg(15,4:6) = [mean(CIE.Duration.Duration_Up_Units_Quantile_Segment_Means.Quant4_Seg3)...
    std(CIE.Duration.Duration_Up_Units_Quantile_Segment_Means.Quant4_Seg3)...
    size(CIE.Duration.Duration_Up_Units_Quantile_Segment_Means,1)];

Summary_data.Up_Quant_Z_All_Seg(16,4:6) = [mean(CIE.Duration.Duration_Up_Units_Quantile_Segment_Means.Quant4_Seg4)...
    std(CIE.Duration.Duration_Up_Units_Quantile_Segment_Means.Quant4_Seg4)...
    size(CIE.Duration.Duration_Up_Units_Quantile_Segment_Means,1)];


%% Quantile Z Down Modulated Segment: All LPs
Summary_data.Down_Quant_Z_All_Seg(1,4:6) = [mean(CIE.Duration.Duration_Down_Units_Quantile_Segment_Means.Quant1_Seg1)...
    std(CIE.Duration.Duration_Down_Units_Quantile_Segment_Means.Quant1_Seg1)...
    size(CIE.Duration.Duration_Down_Units_Quantile_Segment_Means,1)];

Summary_data.Down_Quant_Z_All_Seg(2,4:6) = [mean(CIE.Duration.Duration_Down_Units_Quantile_Segment_Means.Quant1_Seg2)...
    std(CIE.Duration.Duration_Down_Units_Quantile_Segment_Means.Quant1_Seg2)...
    size(CIE.Duration.Duration_Down_Units_Quantile_Segment_Means,1)];

Summary_data.Down_Quant_Z_All_Seg(3,4:6) = [mean(CIE.Duration.Duration_Down_Units_Quantile_Segment_Means.Quant1_Seg3)...
    std(CIE.Duration.Duration_Down_Units_Quantile_Segment_Means.Quant1_Seg3)...
    size(CIE.Duration.Duration_Down_Units_Quantile_Segment_Means,1)];

Summary_data.Down_Quant_Z_All_Seg(4,4:6) = [mean(CIE.Duration.Duration_Down_Units_Quantile_Segment_Means.Quant1_Seg4)...
    std(CIE.Duration.Duration_Down_Units_Quantile_Segment_Means.Quant1_Seg4)...
    size(CIE.Duration.Duration_Down_Units_Quantile_Segment_Means,1)];



Summary_data.Down_Quant_Z_All_Seg(5,4:6) = [mean(CIE.Duration.Duration_Down_Units_Quantile_Segment_Means.Quant2_Seg1)...
    std(CIE.Duration.Duration_Down_Units_Quantile_Segment_Means.Quant2_Seg1)...
    size(CIE.Duration.Duration_Down_Units_Quantile_Segment_Means,1)];

Summary_data.Down_Quant_Z_All_Seg(6,4:6) = [mean(CIE.Duration.Duration_Down_Units_Quantile_Segment_Means.Quant2_Seg2)...
    std(CIE.Duration.Duration_Down_Units_Quantile_Segment_Means.Quant2_Seg2)...
    size(CIE.Duration.Duration_Down_Units_Quantile_Segment_Means,1)];

Summary_data.Down_Quant_Z_All_Seg(7,4:6) = [mean(CIE.Duration.Duration_Down_Units_Quantile_Segment_Means.Quant2_Seg3)...
    std(CIE.Duration.Duration_Down_Units_Quantile_Segment_Means.Quant2_Seg3)...
    size(CIE.Duration.Duration_Down_Units_Quantile_Segment_Means,1)];

Summary_data.Down_Quant_Z_All_Seg(8,4:6) = [mean(CIE.Duration.Duration_Down_Units_Quantile_Segment_Means.Quant2_Seg4)...
    std(CIE.Duration.Duration_Down_Units_Quantile_Segment_Means.Quant2_Seg4)...
    size(CIE.Duration.Duration_Down_Units_Quantile_Segment_Means,1)];



Summary_data.Down_Quant_Z_All_Seg(9,4:6) = [mean(CIE.Duration.Duration_Down_Units_Quantile_Segment_Means.Quant3_Seg1)...
    std(CIE.Duration.Duration_Down_Units_Quantile_Segment_Means.Quant3_Seg1)...
    size(CIE.Duration.Duration_Down_Units_Quantile_Segment_Means,1)];

Summary_data.Down_Quant_Z_All_Seg(10,4:6) = [mean(CIE.Duration.Duration_Down_Units_Quantile_Segment_Means.Quant3_Seg2)...
    std(CIE.Duration.Duration_Down_Units_Quantile_Segment_Means.Quant3_Seg2)...
    size(CIE.Duration.Duration_Down_Units_Quantile_Segment_Means,1)];

Summary_data.Down_Quant_Z_All_Seg(11,4:6) = [mean(CIE.Duration.Duration_Down_Units_Quantile_Segment_Means.Quant3_Seg3)...
    std(CIE.Duration.Duration_Down_Units_Quantile_Segment_Means.Quant3_Seg3)...
    size(CIE.Duration.Duration_Down_Units_Quantile_Segment_Means,1)];

Summary_data.Down_Quant_Z_All_Seg(12,4:6) = [mean(CIE.Duration.Duration_Down_Units_Quantile_Segment_Means.Quant3_Seg4)...
    std(CIE.Duration.Duration_Down_Units_Quantile_Segment_Means.Quant3_Seg4)...
    size(CIE.Duration.Duration_Down_Units_Quantile_Segment_Means,1)];



Summary_data.Down_Quant_Z_All_Seg(13,4:6) = [mean(CIE.Duration.Duration_Down_Units_Quantile_Segment_Means.Quant4_Seg1)...
    std(CIE.Duration.Duration_Down_Units_Quantile_Segment_Means.Quant4_Seg1)...
    size(CIE.Duration.Duration_Down_Units_Quantile_Segment_Means,1)];

Summary_data.Down_Quant_Z_All_Seg(14,4:6) = [mean(CIE.Duration.Duration_Down_Units_Quantile_Segment_Means.Quant4_Seg2)...
    std(CIE.Duration.Duration_Down_Units_Quantile_Segment_Means.Quant4_Seg2)...
    size(CIE.Duration.Duration_Down_Units_Quantile_Segment_Means,1)];

Summary_data.Down_Quant_Z_All_Seg(15,4:6) = [mean(CIE.Duration.Duration_Down_Units_Quantile_Segment_Means.Quant4_Seg3)...
    std(CIE.Duration.Duration_Down_Units_Quantile_Segment_Means.Quant4_Seg3)...
    size(CIE.Duration.Duration_Down_Units_Quantile_Segment_Means,1)];

Summary_data.Down_Quant_Z_All_Seg(16,4:6) = [mean(CIE.Duration.Duration_Down_Units_Quantile_Segment_Means.Quant4_Seg4)...
    std(CIE.Duration.Duration_Down_Units_Quantile_Segment_Means.Quant4_Seg4)...
    size(CIE.Duration.Duration_Down_Units_Quantile_Segment_Means,1)];











%% Unit Spike Proportion


Summary_data.UnitProp_Up_Air = round(Air.Duration.Duration_Up_Units_Quantile_Segment_Spike_Means{:,18} * 100);
Summary_data.UnitProp_Up_CIE = round(CIE.Duration.Duration_Up_Units_Quantile_Segment_Spike_Means{:,18} * 100);
Summary_data.UnitProp_Down_Air = round(Air.Duration.Duration_Down_Units_Quantile_Segment_Spike_Means{:,18} * 100);
Summary_data.UnitProp_Down_CIE = round(CIE.Duration.Duration_Down_Units_Quantile_Segment_Spike_Means{:,18} * 100);